---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
        exclude: \.sh$
    -   id: check-case-conflict
        exclude: \.sh$
    -   id: check-json
        exclude: \.sh$
    -   id: check-merge-conflict
        exclude: \.sh$
    -   id: check-toml
        exclude: \.sh$
    -   id: check-yaml
        exclude: \.sh$
    -   id: end-of-file-fixer
        exclude: \.sh$
    -   id: mixed-line-ending
        exclude: \.sh$
    -   id: trailing-whitespace
        exclude: \.sh$

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
    -   id: black
        args: [--config, pyproject.toml]
        exclude: \.sh$

-   repo: https://github.com/pyCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: [--config, .flake8, --verbose]
        exclude: \.sh$
