name: lnrgst-mca
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - nibabel
  - nilearn
  - jupyter
  - ipykernel
  - pip:
      - gif
